dist: bionic

language: go
go:
  - "1.13"
  - "1.15"
  - master
  
script:
  - go test -race -coverprofile=pqdsn.out -covermode=atomic
  - go test -benchmem -bench .

after_script:
  - bash <(curl -s https://codecov.io/bash) -f '*.out'
